env:
    DEVICE_CODENAME: tapas # Enter your device codename
    ROMREPO: https://github.com/The-Clover-Project/manifest.git -b 16-qpr1 # Enter ROM repo link
    LOCALMANIFEST: # Enter local_manifest link
    MAKEFILENAME: clover_tapas # Enter makefile name (example: aosp_fleur)
    VARIANT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: mka clover -j$(nproc --all) # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[!cf4df094911df00fa94f3a5f289288607b54f9eb22aea58af20170d4d5f87483bf6e6ecb28580aa5db0f5f36b36ab735!]"
    
# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
